### ISSUE TITLE
can't execute command

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/puppetlabs-ibm_installation_manager#5]
I get this error whenever I run this code and all other instances of ibm_pkg.  Did this ever work?  Seems like it should.   

```puppet
ibm_pkg { 'com.ibm.websphere.NDTRIAL.v85':
  ensure     => 'present',
  package    => 'com.ibm.websphere.NDTRIAL.v85',
  version    => '8.5.5000.20130514_1044',
  target     => '/opt/IBM/WebSphere/AppServer',
  repository => '/opt/IBM/repository.config',
  imcl_path  => '/opt/Apps/WebSphere/was8.5/product/eclipse/tools/imcl'
}

```

```
Debug: Ibm_pkg[com.ibm.websphere.NDTRIAL.v85](provider=imcl): Executing '' to find processes that match /opt/IBM/WebSphere/AppServer
Error: Could not set 'present' on ensure: no implicit conversion of nil into String at 11:/etc/puppet/modules/websphere_instance/tests/init.pp
Error: Could not set 'present' on ensure: no implicit conversion of nil into String at 11:/etc/puppet/modules/websphere_instance/tests/init.pp
Wrapped exception:
no implicit conversion of nil into String
Error: /Stage[main]/Main/Ibm_pkg[com.ibm.websphere.NDTRIAL.v85]/ensure: change from absent to present failed: Could not set 'present' on ensure: no implicit conversion of nil into String at 11:/etc/puppet/modules/websphere_instance/tests/init.pp

```

**Comment by bFekete** [comment]
Correlates to issue #7.

**Comment by logicminds** [comment]
I did fix this in my branch, but that code never got merged.  However, the process stuff is still broken as it fails to restart or stop the process.  But I am not getting that error anymore.

My code was cherry-picked a while ago before I fixed a bunch of issues.  

https://github.com/puppetlabs/puppetlabs-ibm_installation_manager/pull/16

I think the changes you want were in the PR above that was never merged.  

https://github.com/logicminds/puppetlabs-ibm_installation_manager/blob/b7d3fa4b5dd17d805ec2e77e1e4a3ef159cafe94/lib/puppet/provider/ibm_pkg/imcl.rb#L106

**Comment by bmjen** [comment]
This is fixed in the latest version I believe.
