### ISSUE TITLE
facter value :ps does not work

### ISSUE THREAD

**Issue by logicminds** [puppetlabs/puppetlabs-ibm_installation_manager#7]
https://github.com/puppetlabs/puppetlabs-ibm_installation_manager/blob/master/lib/puppet/provider/ibm_pkg/imcl.rb#L104e

This doesn't work on my machine,   Was there supposed to be a ps fact?

**Comment by bFekete** [comment]
@logicminds ps fact was removed in PE2015. https://docs.puppetlabs.com/facter/3.0/release_notes.html#break-removed-six-facts

**Comment by bmjen** [comment]
This was addressed in the latest refactor of the ibm_pkg provider. #11
